
framework:
  mailer:
    dsn: '%env(MAILER_DSN)%'
    message_bus: false
    envelope:
            # sender: 'fabien@example.com'
            recipients: ['admin@studioprestge.com']
    headers:
        # From: 'Fabien <fabien@example.com>'
        Bcc: 'baz@example.com'
        X-Custom-Header: 'foobar'